name: CI-Python
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: install requirments
      run: pip3 install -r requirements.txt -t .

  Test:
    needs: Build
    runs-on: self-hosted
    steps:
    - name: run & test the app
      run: python3 app.py &
    - run: sleep 5 && curl localhost:8080
    
  Package:
    needs: Test
    runs-on: self-hosted
    steps:

    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
         artifacts: "release.zip"
         token: ${{ secrets.GITHUB_TOKEN }}
